language: python
python:
  - "2.7"

install:
  - python setup.py -q install
  - pip install -r requirements_test.txt --use-mirrors

#script: LD_LIBRARY_PATH="$HOME/minisat/lib:$LD_LIBRARY_PATH" PATH="$HOME/bin:$PATH" python setup.py test
script: python setup.py test

before_install:
 - git clone https://github.com/niklasso/minisat.git
 - cd minisat && make config prefix=/usr && make && sudo make install && cd -

notifications:
  email:
    recipients:
      - dr@nwebs.de
