language: python
python:
  - "2.7"

install:
  - python setup.py -q install
  - pip install -r requirements_test.txt --use-mirrors

script: LD_LIBRARY_PATH="$HOME/minisat/lib:$LD_LIBRARY_PATH" PATH="$HOME/bin:$PATH" python setup.py test

before_install:
 - make minisat_to_home_bin

notifications:
  email:
    recipients:
      - dr@nwebs.de
