language: python
python:
  - "2.7"

install:
  - python setup.py -q install
  - pip install -r requirements_test.txt --use-mirrors

#script: LD_LIBRARY_PATH="$HOME/minisat/lib:$LD_LIBRARY_PATH" PATH="$HOME/bin:$PATH" python setup.py test
script: python setup.py test

before_install:
 - wget http://minisat.se/downloads/minisat2-070721.zip
 - unzip minisat2-070721.zip
 - cd minisat/core && make
 - cd -
 - mv minisat/core/minisat tests/
 - rm -Rf minisat

notifications:
  email:
    recipients:
      - dr@nwebs.de
